# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeffrey Young's Blog
email: jeff(seven)y@.com
description: > # this means to ignore newlines until "baseurl:"
  Jeffrey's personal Tech Blog.
baseurl: "/TechBlog/" # the subpath of your site, e.g. /blog
url: "http://null5432.github.io" # the base hostname & protocol for your site
twitter_username: null5432
github_username:  null5432

# Build settings
markdown: kramdown
